// PLACEHOLDER — this file is regenerated by `flutterfire configure`.
//
// Run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That will overwrite this file with platform-specific Firebase config for
// Android / iOS / web / macOS. Do not edit manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return _placeholder('web');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return _placeholder('android');
      case TargetPlatform.iOS:     return _placeholder('ios');
      case TargetPlatform.macOS:   return _placeholder('macos');
      default:
        throw UnsupportedError('Run `flutterfire configure` first.');
    }
  }

  static FirebaseOptions _placeholder(String platform) => FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    authDomain: 'REPLACE_ME.firebaseapp.com',
    storageBucket: 'REPLACE_ME.appspot.com',
  );
}
