import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'theme.dart';
import 'firebase_options.dart' as fbopts; // generated by `flutterfire configure`
import 'services/auth_service.dart';
import 'screens/landing_screen.dart';
import 'screens/dashboard_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: fbopts.DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const SabirUfoApp());
}

class SabirUfoApp extends StatelessWidget {
  const SabirUfoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sabir UFO · Sighting & Research',
      debugShowCheckedModeBanner: false,
      theme: SabirUfoTheme.build(),
      home: const _Root(),
    );
  }
}

class _Root extends StatelessWidget {
  const _Root();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
      stream: AuthService.instance.userStream,
      builder: (context, snap) {
        if (!snap.hasData || snap.data == null) {
          return const LandingScreen();
        }
        return const DashboardScreen();
      },
    );
  }
}
